//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBC.ROPP.Shared.Translation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBC.ROPP.Shared.Translation.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant containt self id.
        /// </summary>
        internal static string CantContainSelf {
            get {
                return ResourceManager.GetString("CantContainSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city with this id does not exist.
        /// </summary>
        internal static string CityNotExist {
            get {
                return ResourceManager.GetString("CityNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be an image.
        /// </summary>
        internal static string FileMustBeAnImage {
            get {
                return ResourceManager.GetString("FileMustBeAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName must be in Georgian or in Latin.
        /// </summary>
        internal static string LastNameMustBeGeorgianOrLatin {
            get {
                return ResourceManager.GetString("LastNameMustBeGeorgianOrLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be over 18.
        /// </summary>
        internal static string MustBeOver18 {
            get {
                return ResourceManager.GetString("MustBeOver18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be either in Georgian or in Latin.
        /// </summary>
        internal static string NameMustBeGeorgianOrLatin {
            get {
                return ResourceManager.GetString("NameMustBeGeorgianOrLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personal number must be 11 digits.
        /// </summary>
        internal static string PersonalNumber11Digits {
            get {
                return ResourceManager.GetString("PersonalNumber11Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physical person does not exist.
        /// </summary>
        internal static string PhysicalPersonNotExist {
            get {
                return ResourceManager.GetString("PhysicalPersonNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to related person with id &apos;0&apos; does not exist.
        /// </summary>
        internal static string RelatedPhysicalPersonNotExist {
            get {
                return ResourceManager.GetString("RelatedPhysicalPersonNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
